package com.karloqvist.timetracker.task

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize

/**
 * @author Karl Öqvist
 *
 * Holds the data for each timed task and is also the entity in the database.
 * Parcelable to be able to save it in SavedState
 *
 * @property title - Name of task visible in app, added by the user
 * @property description - Description of task visible in app, added by the user
 * @property id - autogenerated to be used as primary key in database
 * @property time - accumulated time for the task since last reset
 * @property historic - accumulated time for the task in total
 */

@Parcelize
@Entity(tableName = "task_table")
class Task(var title: String, var description: String) : Parcelable {
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0
    var time: Int = 0
    var historicTime: Int = 0
}